#
# TraceEtw project AppVeyor build configuration
#

version: 1.1.{build}

branches:
  except:
    - gh-pages

os: Visual Studio 2015

configuration:
  - Release
  - Debug

assembly_info:
  patch: true
  file: AssemblyInfo.cs
  assembly_version: "{version}.0"
  assembly_file_version: "{version}.0"
  assembly_informational_version: "{version}.0"

before_build:
  - cmd: set BUILDCONFIGURATION=%CONFIGURATION%
  - cmd: set BUILD_NUMBER=%APPVEYOR_BUILD_NUMBER%
  - cmd: nuget restore TraceEtw\TraceEtw.sln

build:
  project: TraceEtw\Build.proj
  verbosity: normal

artifacts:
  - path: 'TraceEtw\artifacts\*.nupkg'

test_script:
  - nunit3-console TraceEtw\EventProviderGeneratorTests\bin\%CONFIGURATION%\EventProviderGeneratorTests.dll --result=EventProviderGeneratorTestsResults.xml;format=AppVeyor
  - vstest.console /logger:Appveyor TraceEtw\%CONFIGURATION%\TraceEtwTests.Desktop.dll

deploy:
  provider: NuGet
  api_key:
    secure: jINaEHhYh83PTuZYPwnkoTDUMB+pTz6UMmeqkWeRnqtZXIuX/Nd3Fyu197viK/vR
  skip_symbols: true
  on:
    appveyor_repo_tag: true
    configuration: Release

cache:
  - TraceEtw\packages -> **\packages.config
